development:
  adapter: postgresql
  database: marks_development
  encoding: utf8
  schema_search_path: public
  pool: 5
  timeout: 5000
  username: test

test:
  adapter: postgresql
  database: marks_test
  encoding: utf8
  schema_search_path: public
  pool: 5
  timeout: 5000
  username: test